config/routes.rb
SimpleVoting::Application.routes.draw do
  devise_for :users

  resources :topics do
    member do
      post 'vote'
    end
  end
  
  root :to => 'topics#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
    
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      # can :read, :all
      can :manage, :sessions
    end
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  attr_accessor :user
  validate :validate_user_votes
  validates_presence_of :title
  after_create :update_user_votes
  belongs_to :user
  
  def vote(u)
    self.user = u
    self.user.votes_left -= 1
    self.votes += 1
    Topic.transaction do
      self.save && self.user.save
    end
  end
  
  def validate_user_votes
    errors[:votes] = 'You do not have any more votes!' if self.user && self.user.votes_left < 0
  end

  def update_user_votes
    user.votes_left += User::NEW_TOPIC_VOTES
    user.save!
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_protected :admin
  
  WEEKLY_VOTES = 2
  NEW_TOPIC_VOTES = 2
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def require_admin
    raise CanCan::AccessDenied if !current_user.admin?
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :authenticate_user!
  include ActionView::Helpers::TextHelper
  def vote
    topic = Topic.find(params[:id])
    if topic.vote(current_user)
      redirect_to root_path, notice: "Thanks for voting! You have #{pluralize(current_user.votes_left,'Vote')} left."
    else
      redirect_to root_path, alert: topic.errors[:votes].first
    end
  end
  
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all(:order => 'votes desc')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = Topic.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(params[:topic].merge({user: current_user}))

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/_nav.html.erb
<% if user_signed_in? %>
    You have <%= pluralize(current_user.votes_left, 'Vote') %> left.
<% end %>
<br/>
<%= link_to 'Create Topic', new_topic_path %>
<br/>
<%= link_to 'View Topics', topics_path %>
<br/>
<% if user_signed_in? %>
    <%= link_to 'Change Password', edit_user_registration_path %>
    <br/>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
<% end %>

app/views/layouts/_notices.html.erb
<% if alert %>
    <p class="alert"><%= alert %></p>
<% end %>

<% if notice %>
    <p id="notice"><%= notice %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleVoting</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container showgrid">
  <div class="span-24 last" id="header">
    <h1>Simple Voting</h1>
  </div>
  <div class="clear span-5" id="nav">
    <%= render partial: 'layouts/nav' %>
  </div>
  <div class="span-19 last" id="content">
    <%= render partial: 'layouts/notices' %>
    <%= yield %>
  </div>
  <div class="clear span-24 last" id="footer">
  </div>
</div>
</body>
</html>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :votes %><br />
    <%= f.number_field :votes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing topics</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Votes</th>
		<th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @topics.each do |topic| %>
  <tr>
    <td><%= topic.title %></td>
    <td><%= pluralize(topic.votes, 'Vote') %></td>
		<td><%= link_to 'Vote!', vote_topic_path(topic), method: :post %></td>
    <td><%= link_to 'Show', topic %></td>
    <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
    <td><%= link_to 'Destroy', topic, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

app/views/topics/new.html.erb
<div class="span-16 prepend-3">
  <h1>New topic</h1>
</div>
<div class="span-5">
  When you create a new topic, you will receive 2 extra votes. Spend them wisely.
</div>
<div class="span-14 last">
  <%= render 'form' %>

  <%= link_to 'Back', topics_path %>
</div>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @topic.title %>
</p>

<p>
  <b>Votes:</b>
  <%= @topic.votes %>
</p>


<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', topics_path %>